### ISSUE TITLE
A few delay and thread tests fail when run under tarpaulin

### ISSUE THREAD

**Issue by ehiggs** [rxRust/rxRust#72]
[Tarpaulin is a test coverage tool for Rust](https://github.com/xd009642/tarpaulin). The good news is that rxRust seems to have 93% coverage which is great! But when running under tarpaulin, I see some test failures:

```
rustup run nightly cargo tarpaulin
```

```
running 119 tests
...............................F.thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/ops/delay.rs:75:8
...............................F..thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/ops/observe_on.rs:164:7
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/ops/observe_on.rs:88:11
.................F.thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/ops/subscribe_on.rs:117:9
.............. 100/119
..........F.thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/subject.rs:451:10
......F
failures:

---- ops::delay::smoke stdout ----
thread 'ops::delay::smoke' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `1`', src/ops/delay.rs:79:3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- ops::observe_on::test::switch_thread stdout ----
thread 'ops::observe_on::test::switch_thread' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/libcore/slice/mod.rs:2791:10

---- ops::subscribe_on::test::new_thread stdout ----
thread 'ops::subscribe_on::test::new_thread' panicked at 'assertion failed: `(left == right)`
  left: `[]`,
 right: `[1, 2, 3, 4]`', src/ops/subscribe_on.rs:123:5

---- subject::test::empty_local_subject_can_convert_to_shared stdout ----
thread 'subject::test::empty_local_subject_can_convert_to_shared' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `100`', src/subject.rs:458:5

---- ops::throttle_time::smoke stdout ----
thread 'ops::throttle_time::smoke' panicked at 'assertion failed: `(left == right)`
  left: `[9, 19, 29, 39, 49, 59, 69, 79, 89]`,
 right: `[9, 19, 29, 39, 49, 59, 69, 79, 89, 99]`', src/ops/throttle_time.rs:221:3


failures:
    ops::delay::smoke
    ops::observe_on::test::switch_thread
    ops::subscribe_on::test::new_thread
    ops::throttle_time::smoke
    subject::test::empty_local_subject_can_convert_to_shared
```

For what it's worth, here is the coverage report:

```
INFO tarpaulin] Coverage Results:
|| Tested/Total Lines:
|| src/observable/connectable_observable.rs: 27/31 +0%
|| src/observable/from.rs: 112/116 +0%
|| src/observable/from_future.rs: 17/17 +0%
|| src/observable/interval.rs: 20/21 +0%
|| src/observable/trivial.rs: 24/24 +0%
|| src/observable.rs: 67/69 +0%
|| src/observer.rs: 10/12 +0%
|| src/ops/average.rs: 42/42 +0%
|| src/ops/count.rs: 16/16 +0%
|| src/ops/delay.rs: 21/24 +0%
|| src/ops/filter.rs: 22/27 +0%
|| src/ops/filter_map.rs: 36/41 +0%
|| src/ops/first.rs: 75/76 +0%
|| src/ops/last.rs: 106/106 +0%
|| src/ops/map.rs: 46/48 +0%
|| src/ops/merge.rs: 97/103 +0%
|| src/ops/minmax.rs: 104/107 +0%
|| src/ops/observe_on.rs: 50/68 +0%
|| src/ops/publish.rs: 10/11 +0%
|| src/ops/reduce.rs: 40/40 +0%
|| src/ops/ref_count.rs: 69/74 +0%
|| src/ops/scan.rs: 58/61 +0%
|| src/ops/subscribe_on.rs: 30/33 +0%
|| src/ops/sum.rs: 24/24 +0%
|| src/ops/take.rs: 51/52 +0%
|| src/ops/take_last.rs: 53/55 +0%
|| src/ops/throttle_time.rs: 71/85 +0%
|| src/ops.rs: 4/4 +0%
|| src/scheduler/thread_pool_scheduler.rs: 7/7 +0%
|| src/scheduler/thread_scheduler.rs: 10/11 +0%
|| src/scheduler.rs: 18/20 +0%
|| src/subject.rs: 134/143 +0%
|| src/subscribable/subscribable_all.rs: 10/11 +0%
|| src/subscribable/subscribable_comp.rs: 4/5 +0%
|| src/subscribable/subscribable_err.rs: 6/6 +0%
|| src/subscribable/subscribable_pure.rs: 6/7 +0%
|| src/subscribable.rs: 1/1 +0%
|| src/subscriber.rs: 74/76 +0%
|| src/subscription.rs: 82/87 +0%
|| src/util.rs: 2/2 +0%
|| 
93.93% coverage, 1656/1763 lines covered, +0% change in coverage
```

**Comment by ehiggs** [comment]
This is probably the same issue as #26.
